theme: jekyll-theme-slate
title: LLM as Thought-Partner
description: Discuss prospects for using LLMs as thought-partners, particularly as a Socratic companion to enhance learning.
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
highlighter: rouge
